apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azurekeyvault-sidecar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: azurekeyvault-sidecar
    spec:
      containers:
      - name: sidecar
        image: ritazh/k8s-azurekeyvault-sidecar
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: VAULT_NAME
          value: k8skv1
        - name: SECRET_NAME
          value: test
        - name: RESOURCE_GROUP
          value: ritakvrg
        - name: CONFIG_FILEPATH
          value: /etc/kubernetes/azure.json
        - name: DIR
          value: /etc/secrets
        volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: secrets
          mountPath: /etc/secrets
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: secrets
        emptyDir: {}
